config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'messages#index'
  resources :messages, only: [:index, :create]

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :integer          not null, primary key
#  body       :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Message < ApplicationRecord
  MAX_BODY_LENGTH = 140

  validates :body,
    presence: true,
    length: { maximum: MAX_BODY_LENGTH }

  after_create do
    NotifyUpdateJob.perform_later(body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_messages

  def index
    @message = Message.new
  end

  def create
    @message = Message.create(create_params)
    if @message.valid?
      ResponseMessageJob.set(wait: 3.seconds).perform_later(@message)
      redirect_to messages_url
    else
      render :index
    end
  end

  private

    def set_messages
      @messages = Message.order(id: :desc).limit(30)
    end

    def create_params
      params.require(:message).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navbar_item(name, path, options = {})
    options = options.merge(
      class: "#{options[:class]} nav-link".strip,
      wrap_tag: "li",
      wrap_class: "nav-item",
    )
    active_link_to(name, path, options)
  end
end

app/views/layouts/application.html.slim
html
  head
    title Demoapp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag    'application'
    = javascript_pack_tag    'application'
  body
    nav.navbar.navbar-expand.navbar-light.bg-light
      .container
        = link_to "Demo App", root_path, class: "navbar-brand"
        button.navbar-toggler(type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-exmapded="false" aria-label="Toggle navigation")
        .collapse.navbar-collapse
          ul.navbar-nav.mr-auto
            = navbar_item "Home", root_path
          ul.navbar-nav
            li.nav-item.dropdown
              a#dropdown_admin.nav-link.dropdown-toggle(data-toggle="dropdown" aria-haspopup="true" aria-expanded="false") Admin
              .dropdown-menu(aria-labelledby="dropdown_admin")
                = link_to "Sidekiq", sidekiq_web_path, target: "_blank", class: "dropdown-item"
    .container.pt-3
      = yield

app/views/messages/index.html.slim
.row.justify-content-lg-center
  .col-lg-9
    = bootstrap_form_for @message do |f|
      .form-row
        .col
          = f.text_area :body
        .col-md-1.col-sm-2.col-3
          label &nbsp;
          = f.submit "Submit"

    - @messages.each do |message|
      .card
        .card-body.clearfix
          p= message.body
          small.float-right(title=message.created_at)
            = time_ago_in_words message.created_at